harry_potter_candies = [
    "Bertie Bott's Every Flavor Beans",
    "Chocolate Frogs",
    "Fizzing Whizzbees",
    "Droobles Best Blowing Gum",
    "Pumpkin Pasties",
    "Cockroach Clusters",
    "Licorice Wands",
    "Sherbet Lemons",
    "Pepper Imps",
    "Chocoballs",
    "Honeydukes Chocolate",
    "Exploding Bonbons",
    "Lemon Sherbets",
    "Toothflossing Stringmints",
    "Fudge Flies",
    "Sugar Quills",
    "Jelly Slugs",
    "Acid Pops",
    "Cauldron Cakes",
    "Blood-Flavored Lollipops",
    "Treacle Tart",
    "Caramel Cobwebs",
    "Fainting Fancies",
    "Pink Coconut Ice",
    "Cinnamon Gobstoppers",
    "Licorice Snaps",
    "Ice Mice",
    "Nougat Nipples",
    "Sherbet Balls",
    "Chocolate Cauldrons",
    "Frosted Fizzballs",
    "Peppermint Toads",
    "Pumpkin Juice",
    "Butterbeer",
    "Firewhisky",
    "Gillywater",
    "Pumpkin Juice",
    "Polyjuice Potion",
    "Amortentia Infused Chocolate",
    "Dungbomb",
    "Fizzing Pumpkin Juice",
    "Ton-Tongue Toffee",
    "Nosebleed Nougat",
    "Blood-Flavored Lollipops",
    "Charm Choc",
    "Muggle Fudge",
    "Cockroach Clusters",
    "Nougat",
    "Sugar Quills",
    "Peppermint Toads",
    "Treacle Tart",
    "Chocolate Cauldrons",
    "Blood Pops",
    "Acid Pops",
    "Puking Pastilles",
    "Jelly Slugs",
    "Exploding Bonbons",
    "Pumpkin Pasties",
    "Chocoballs",
    "Honeydukes Chocolate",
    "Fudge Flies",
    "Liquorice Wands",
    "Sherbet Lemons",
    "Cauldron Cakes",
    "Butterbeer",
    "Pumpkin Juice",
    "Fizzing Whizzbees",
    "Toothflossing Stringmints",
    "Caramel Cobwebs",
    "Fainting Fancies",
    "Pink Coconut Ice",
    "Pepper Imps",
    "Licorice Snaps",
    "Ice Mice",
    "Nougat Nipples",
    "Sherbet Balls",
    "Frosted Fizzballs",
    "Fizzing Pumpkin Juice",
    "Chocolate Frogs",
]
